import { environment } from '../environments/environment';

export const CONSTANTS = Object.freeze({
    PAGEURL_MAIN: {
      MAINURL:environment.MAINURL,
      GAMEURL:environment.GAMEURL,
      GAMEURL1:environment.GAMEURL1,
    },

    PAYMENT: {
//      ACCESSCODE: 'AVDN79FG25BL75NDLB',
//      WORKINGCODE: 'F5B281DB934E01548FA3DBC05C954EE9',
      ACCESSCODE: environment.ACCESSCODE,
      WORKINGCODE: environment.WORKINGCODE,
      MERCHENTID: environment.MERCHENTID,
      REDIRECT_URL: environment.REDIRECT_URL,
      CANCEL_URL: environment.CANCEL_URL
    },
    SERVICES: {
        HEADERS: { 'Content-Type': 'application/json',
                  'Accept': 'application/json',
                  'token': localStorage.getItem('token')
                }

    },
    PAGETITLE: {
        HOME: 'Premium Early Childhood Development | Nidara-Children',
        ABOUTUS: 'About Us | Nidara-Children',
        OURHISTORY: 'Our History | Nidara-Children',
        TESTIMONALS: 'Testimonals | Nidara-Children',
        TINA : 'Tina | Nidara-Children',
        HEALTHWHOLECHILDDEVELOPMENT: 'Health Whole Child Development | Nidara-Children',
        HEALTHCAREPROVIDERS : 'Healthcare Providres | Nidara-Children',
        PERSONALIZEDLEARNING: 'Personalized Learning | Nidara-Children',
        CONTACTUS: 'Contact Us | Nidara-Children',
        COMPANY: 'Company | Nidara-Children',
        FOUNDARSWELCOME: 'Founders Welcome | Nidara-Children',
        TERMSOFUSE: 'Terms Of Use | Nidara-Children',
        NOTICEOFPRIVACYPRACTICES: 'Notice Of Privacy Practices | Nidara-Children',
        PRIVACYPOLICY: 'Privacy Policy | Nidara-Children',
        COOKIESPOLICY: 'Cookie Policy | Nidara-Children',
        EDITORSPOLICY: 'Editorial Policy | Nidara-Children',
        SITEMAP: 'Sitemap | Nidara-Children',
        EDUCATORS: 'Educators | Nidara-Children',
        STORIES: 'Stories | Nidara-Children',
        FAQS: 'Faqs | Nidara-Children',
        NCBLOG: 'NC-Blog | Nidara-Children',
        INTERESTEXPLORATION: 'Interest Exploration | Nidara-Children',
        GIRL : 'Girl | Nidara-Children',
        BOY: 'Boy | Nidara-Children',
        SIGNIN: 'Sign in | Nidara-Children',
        WEBADMIN: 'NC-Admin',
        CHANGEPASSWORD: 'Nidara - ChangePassword',
        RESETPASSWORD: 'Nidara - ResetPassword',
        FORGOTPASSWORD: 'Nidara - ForgotPassword',
        DASHBOARD: 'Nidara - Dashboard',
        CHILDRENPROFILES: 'Nidara - Children Profiles',
        SCHOOLINFORMATION: 'Nidara - School Information',
        CAREGIVERINFO: 'Nidara - CaregiverInfo',
        CAREGIVERGUIDE: 'Nidara - Caregiver Guide',
        CHILDRENEDUINFORMATION: 'Nidara - Edu Information',
        CHILDPROFILE: 'Nidara - child-profileid-register',
        CHILDRENNUTRITION: 'Nidara - Nutrition',
        DAILYSCHEDULER: 'Nidara - Daily Scheduler',
        RESIDENCEDETAIL: 'Nidara - Residence Detail',
        PARENTSMYACCOUNT: 'Nidara - My Account',
        REACTIVEACCOUNT: 'Nidara - Reactive Account',
        PHYSICALINFO: 'Nidara - Physical Info',
        MEDICALCONCERN: 'Nidara - Medical Concern',
        DEACTIVEACCOUNT: 'Nidara - Deactive Account',
        CHILDRENFRINEDSINFO: 'Nidara - Children Friend Info',
        CHILDRENFAMILYINFO: 'Nidara - Children Family Info',
        CHILDRENLANGUAGEINFO: 'Nidara - Children Language Info',
        BILLINGADDRESS: 'Nidara - Billing Address',
        DAILYROUTINE: 'Nidara - Daily Routine',
        QUICKSTARTGUIDE: 'Nidara - Quick Start Guide',
        CHILDRENREGISTER: 'Nidara - Children Register',
        ACTIVATENIDARA: 'Nidara - Activate Nidara',
        DAILYSESSION: 'Nidara - Daily Session',
        CHILDRENINTERESTDEV: 'Nidara - Children Interest Development',
        PAYMENTINFO: 'Nidara -Payment Info'
    },
    PAGEURL: {
        HOME: 'Home',
        SIGNIN: 'signin',
        SIGNUP: 'signup',
        ADMIN: 'admin-dashboard',
        CHILDPROFILEREG: 'child-profileid-register',
        DASHBOARD: {
            PARENTS: 'dashboard',
            CHILDREN: 'children-dashboard',
            DOCTOR: 'doctor',
        },
        SUPPORT: 'support',
        FORGOTPASSWORD: 'forgotpassword',
        CHANGEPASSWORD: 'changepassword',
        RESETPASSWORD: 'resetpassword',
        CHILDRENPROFILE: 'profiles',
        SCHOOLINFORMATION: 'school-information',
        CAREGIVERINFO: 'caregiver-info',
        CAREGIVERGUIDE: 'caregiver-guide',
        CHILDRENEDUINFORAMTION: 'edu-information',
        CHILDRENNUTRITION: 'nutrition',
        DAILYSCHEDULER: 'daily-schedule',
        RESIDENCEDETAIL: 'residence-detail',
        PARENTSMYACCOUNT: 'parents-account',
        REACTIVEACCOUNT: 'reactive-detail',
        PHYSICALINFO: 'physical-info',
        MEDICALCONCERN: 'medical-concern',
        DEACTIVEACCOUNT: 'account-deactive',
        CHILDRENFRINEDSINFO: 'friend-info',
        CHILDRENFAMILYINFO: 'family-info',
        CHILDRENLANGUAGEINFO: 'language-info',
        BILLINGADDRESS: 'billing-address',
        DAILYROUTINE: 'daily-routine',
        PARENTQUESTIONREPORT: 'parent-questionar',
        PARENTGAMEREPORT: 'parent-game',
        QUICKSTARTGUIDE: 'quick-start-guide',
        CHILDRENREGISTER: 'children-register',
        ACTIVATENIDARA: 'activate-nidara',
        DAILYSESSION: 'daily-session',
        CHILDRENINTERESTDEV: 'interest-deve',
        PAYMENTINFO: 'payment-info',
        NOTFOUND: '404'
    }
});
